### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by Grindv1k** [fluffysquirrels/mqtt-async-client-rs#10]
Hi, thanks for this nice async mqtt client!

Just putting the interest out there for websocket support.
Would appreciate it in the future.

**Comment by fluffysquirrels** [comment]
Thanks for your interest in the crate, I'll add it to the list!

Just out of curiosity, are you using an MQTT broker that has support for WebSockets but not TCP/IP? If so which one?

**Comment by Grindv1k** [comment]
No, using Mosquitto.
I had some issues using this client via TCP/IP and a frontend web-app which required websockets.
Both could connect to the broker and publish messages, but didn't hear each other.
So I wished for this client to be able to use websockets.

The situation fixed itself when I found it I was running two brokers in parallel, one getting the TCP/IP traffic and the other the websocket traffic. Whoops 😄 

This client has worked solidly so far! Thanks again

**Comment by fluffysquirrels** [comment]
Glad you got it working in the end.

I'll leave this ticket up to keep track of the WebSocket feature, but it'll probably be a lowish priority while there is a workaround.

**Comment by stabler** [comment]
I would like to register my interest in this too!

I'm connecting to the AWS IoT MQTT implementation. In my use-case I have many 'things' (end devices that are connecting over MQTT using X.509 certificates), and I am in the process of building a management application which will run on an EC2 instance. 

I would like to authenticate the management application using Amazon's 'Signature Version 4', because that allows me to manage permissions using the AWS IAM infrastructure (as opposed to treating the server like a 'thing' and using certificates/policies). I will also need to publish and subscribe.

Based on those goals, the only protocol Amazon exposes is MQTT over WebSocket ([source](https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html)). I have working code that uses Paho, but I would much prefer to use mqttrs so I don't need to use OpenSSL!

If it's helpful, I can support with examples for connecting to AWS IoT. I took a look at making the changes myself, but I don't think I have the context to do a good job on the API to the builder to disambiguate between TCP and WebSocket- although if you point me in the right direction I might be able to take a shot at it. It looks like `AsyncStream` is well set up to optionally support a tokio based websocket crate like [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite).

**Comment by keysightschaefer** [comment]
I will also pile on for the WebSocket support.  Specifically  "wss://"  

The issue here is that many firewalls will allow outbound HTTPS connections  but will block "random" ports like 1883.  So for people building systems and not trying to change some IT departments policies about firewalls ( however misinformed ),  this is a very very helpful feature.

**Comment by stabler** [comment]
Thanks @JarredAllen !

**Comment by fluffysquirrels** [comment]
I think this one is sorted, released in v0.3.0! Thanks again to @JarredAllen .
