### ISSUE TITLE
Avoid allocations in publications

### ISSUE THREAD

**Issue by schungx** [fluffysquirrels/mqtt-async-client-rs#11]
It seems inefficient to always build a `Vec<u8>` to hold publish data if the data length is relatively constant.  For example, if always publishing i32 or f32/f64, etc., it is a waste to always have to create a new `Vec<u8>` every time.

A suggestion is to make `Publish` with a minimum buffer size (something like 8 bytes should work for most primitive data types):

~~~rust
pub enum Payload {
    Fixed([u8; 8], u8),    // 8-byte buffer, length
    Vec(Vec<u8>),        // Variable length
}

pub struct Publish {
    topic: Cow<'static, str>,
    payload: Payload,
    qos: QoS,
    retain: bool,
}

fn new_4<T: Into<Cow<'static, str>>(topic: T, payload: [u8; 4]) -> Publish {
        let mut buf = [0_u8; 8];
        buf[0..4].copy_from_slice(payload);
        Publish { topic: topic.into(), payload: Payload::Fixed(buf, 4), qos: QoS::AtMostOnce, retain: false, }
    }
}

pub fn new_i32<T: Into<Cow<'static, str>>(topic: T, payload: i32) -> Publish {
    Self::new_4(topic, payload.as_le_bytes())
}
~~~

This also uses `Cow<'static, str>` to avoid allocations when topic names are constants (which may happen a LOT).

**Comment by schungx** [comment]
A new PR is submitted with the changes.

**Comment by fluffysquirrels** [comment]
Thanks for your interest in the crate, these are intriguing ideas.

For optimisations like this I'd probably like to see [benchmarks](https://doc.rust-lang.org/unstable-book/library-features/test.html) to prove that this actually makes publish faster. Could you put together some microbenchmarks reading and writing to Cow<'static, str>, String, Vec<u8> and your `Payload` to show your versions are faster?

I'm trying to support compiling under the Rust stable toolchain, so please keep the benchmarks (requiring the `#![feature(test)]` attribute on the crate) in a separate bench test library or behind a Cargo feature flag `bench`.

**Comment by schungx** [comment]
> I'm trying to support compiling under the Rust stable toolchain

That's strange... I have been using stable all this time and there hasn't been a problem...

**Comment by schungx** [comment]
As for benchmarks, I am not sure how it would be meaningful as the network latency is likely to dwarf any savings on the publication side...  Admittedly it is not going to be an earth-shattering optimization because very few clients are going to do rapid-fire publishes...  It may only be meaningful for very resource-constrained devices.

The optimizations are not difficult and they only tune for the common scenario: repeat publishes to the same topics with small amounts of data.

**Comment by fluffysquirrels** [comment]
I agree that network latency could well dwarf any savings, and that these changes could be most helpful in devices with limited memory.

I did a little Googling and there's actually a crate -- [smallvec](https://crates.io/crates/smallvec) -- that does this same optimisation (store data inline when small, use a Vec when enough elements are stored). What's more surprising is that in the benchmarks [here](http://troubles.md/posts/improving-smallvec/) smallvec often performs worse than a plain vector because heap allocation is so fast.

So I'm not sure about the Payload change: adding an extra dependency and some cognitive load for the user for possibly a slight decrease in performance.

As for the topic name, using `Cow` is an interesting idea but I'm not sure about that change either without seeing any benchmarks.

**Comment by schungx** [comment]
> I did a little Googling and there's actually a crate -- [smallvec](https://crates.io/crates/smallvec)

I didn't know that!  Good find!

**Comment by fluffysquirrels** [comment]
Thanks for the input but I'm going to close this now without positive benchmarks to show it helps.
